package com.hackfire.hftube.auth

import android.content.Context
import android.webkit.CookieManager
import java.io.File

/**
 * Captured cookies live in app-private internal storage
 * (filesDir/cookies/youtube_cookies.txt) — never external storage, never
 * anywhere a git operation could see it. This is intentionally outside the
 * repo entirely, not just gitignored: it's a runtime file that only ever
 * exists on the device.
 *
 * Written in the Netscape cookie-file format because that's what yt-dlp's
 * --cookies flag expects.
 */
object CookieStore {

    private const val COOKIE_DIR = "cookies"
    private const val COOKIE_FILE = "youtube_cookies.txt"
    private const val PREFS_NAME = "hf_tube_auth"
    private const val KEY_HAS_SESSION = "has_session"

    fun cookieFile(context: Context): File {
        val dir = File(context.filesDir, COOKIE_DIR)
        if (!dir.exists()) dir.mkdirs()
        return File(dir, COOKIE_FILE)
    }

    /** True once a sign-in has completed and cookies were captured. */
    fun hasSession(context: Context): Boolean {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        return prefs.getBoolean(KEY_HAS_SESSION, false) && cookieFile(context).exists()
    }

    /**
     * Pulls the current cookies CookieManager holds for youtube.com/google.com
     * and writes them out in Netscape format. Call this right after a
     * WebView finishes navigating to a page that confirms sign-in succeeded.
     */
    fun captureFromWebView(context: Context) {
        val manager = CookieManager.getInstance()
        val domains = listOf(
            "https://www.youtube.com",
            "https://youtube.com",
            "https://.youtube.com",
            "https://accounts.google.com"
        )

        val lines = mutableListOf("# Netscape HTTP Cookie File", "# Generated by HF-Tube — do not commit this file")
        domains.forEach { domain ->
            val cookieHeader = manager.getCookie(domain) ?: return@forEach
            val host = domain.removePrefix("https://")
            cookieHeader.split(";").forEach { pair ->
                val trimmed = pair.trim()
                if (trimmed.isEmpty()) return@forEach
                val eq = trimmed.indexOf('=')
                if (eq <= 0) return@forEach
                val name = trimmed.substring(0, eq)
                val value = trimmed.substring(eq + 1)
                // domain, includeSubdomains, path, secure, expiry(0=session), name, value
                lines += listOf(".$host", "TRUE", "/", "TRUE", "0", name, value).joinToString("\t")
            }
        }

        cookieFile(context).writeText(lines.joinToString("\n"))
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            .edit().putBoolean(KEY_HAS_SESSION, true).apply()
    }

    fun clearSession(context: Context) {
        cookieFile(context).delete()
        CookieManager.getInstance().removeAllCookies(null)
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            .edit().putBoolean(KEY_HAS_SESSION, false).apply()
    }
}
